name: Build and deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install and lint
        working-directory: ./scripts
        run: |
          yarn install
          yarn lint
      - name: update papers
        working-directory: ./scripts
        run: |
          rm ../data/**/_Example.ttl
          yarn papers
      - name: build
        working-directory: ./scripts
        run: yarn build
      # deploy when running on master
      - name: prepare deploy
        if: github.ref == 'refs/heads/master'
        working-directory: ./scripts
        run: |
          cp exoframe.json public/
          cp Dockerfile public/
      - name: deploy
        if: github.ref == 'refs/heads/master'
        working-directory: ./scripts/public
        run: npx exoframe -u -e https://exoframe.codezen.net -t $EXO_TOKEN
        env:
          EXO_TOKEN: ${{ secrets.EXO_TOKEN }}
